import time
import os
print('ahoj!')
time.sleep(1)
print('hrajes ted moji minihru...')
time.sleep(0.3)
print("██╗  ██╗██╗      █████╗ ██████╗  ██████╗ ██╗   ██╗██╗   ██╗")
time.sleep(0.3)
print("██║  ██║██║     ██╔══██╗██╔══██╗██╔═══██╗██║   ██║╚██╗ ██╔╝")
time.sleep(0.3)
print("███████║██║     ███████║██║  ██║██║   ██║██║   ██║ ╚████╔╝")
time.sleep(0.3)
print("██╔══██║██║     ██╔══██║██║  ██║██║   ██║╚██╗ ██╔╝  ╚██╔╝")
time.sleep(0.3)
print("██║  ██║███████╗██║  ██║██████╔╝╚██████╔╝ ╚████╔╝    ██║")
time.sleep(0.3)
print("╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝  ╚═════╝   ╚═══╝     ╚═╝")
print("")
time.sleep(0.3)
print("███████╗██████╗ ██████╗  █████╗ ████████╗███████╗██╗  ██╗")
time.sleep(0.3)
print("██╔════╝██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██╔════╝██║ ██╔╝")
time.sleep(0.3)
print("███████╗██████╔╝██████╔╝███████║   ██║   █████╗  █████╔╝")
time.sleep(0.3)
print("╚════██║██╔═══╝ ██╔══██╗██╔══██║   ██║   ██╔══╝  ██╔═██╗")
time.sleep(0.3)
print("███████║██║     ██║  ██║██║  ██║   ██║   ███████╗██║  ██╗")
time.sleep(0.3)
print("╚══════╝╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝")
time.sleep(0.3)
print("")
print("---Dostaň se k ledničce, aniž by si tě někdo všimnul!---")
time.sleep(4)
print('tvym ukolem je, aby ses ty, hraci, dostal k lednicce, a aby si nedostal naprdel...')
time.sleep(1)
print('jdes do toho?')
anone=input('').strip().lower()
while anone!='ano' and anone!='a' and anone!='jj' and anone!='ne' and anone!='nn' and anone!='n' :
    print('ty ses kokot ano nebo ne')
    anone=input('').strip().lower()
    
if anone=='ano' or anone=='a' or anone=='jj':
    print('tak do toho jupii')

elif anone=='n' or anone=='ne' or anone=='nn':
    print('tak di do pice')
    time.sleep(3)
    os.system('cls')
    exit()

print('zaciname...')
print('.'), time.sleep(1)
time.sleep(1)
print('')
print('')
print('')
print('vzbudil ses a uslysel, jak ti zacalo strasne krucet v brise...')
time.sleep(2)
print('jako kdyby si tam mel draka')
time.sleep(2)
print('tak ted.. mas na vyber.')
time.sleep(1)
print('A --> opustit pokoj')
print('B --> pohladit si brisko a jit dal spat')
abodp=input('').upper()
while abodp!='A' and abodp!='B':
    print('tak ses debil odpovez normalne')
    abodp=input('').upper()
if abodp=="A" :
    print('takze... vychazis ven, a jses na chodbe.')
    time.sleep(1)
    print('momentalne se nachazis vedle sveho pokoje, v chodbicce na druhem patre.')
    time.sleep(1)
    print('vsechny dvere jsou zavrene. ale hluk jde stejnak slyset...')
    print('vedle tveho pokoje je dalsi pokoj, kde spi tvi sourozenci.')
    time.sleep(1)
    print('vedle pokoce tvyj sourozencu je pokoj rdicu, kdese ale sviti...')
    time.sleep(1)
    print('vpravo od tveho pokoje je koupelna.')
    print('')
    print('kam pujdes?')
    print('')
    time.sleep(2)
    print('A --> pokoj sourozencu')
    print('B --> pokoj rodicu')
    print('C --> koupelna')
    print('D --> dolu')
    abcd1=input('').strip().upper()
    while abcd1!="A" and abcd1!='B' and abcd1!= 'C' and abcd1!='D':
        print('DEBILE PIS NORMALNE KAM PUJDES')
        abcd1=input('').strip().upper()

    if abcd1=='A': #pokoj sourozencu
        print('kmo ty ses na hlavu...', end='\r')
        time.sleep(3)
        print('sel si do pokoje sourozencu...')
        time.sleep(3)
        print('.', time.sleep(1), '.', time.sleep(1), '.')
        time.sleep(2)
        print('a sezral si jednoho z nich.')
        time.sleep(1)
        print('spokojeny?', time.sleep(1), " no to je jedno...")
        time.sleep(2)
        print('sel si spat napapany. konec')
        time.sleep(3)
        os.system('cls')
        print("████████╗██╗  ██╗███████╗    ███████╗███╗   ██╗██████╗ ")
        time.sleep(0.3)
        print("╚══██╔══╝██║  ██║██╔════╝    ██╔════╝████╗  ██║██╔══██╗")
        time.sleep(0.3)
        print("   ██║   ███████║█████╗      █████╗  ██╔██╗ ██║██║  ██║")
        time.sleep(0.3)
        print("   ██║   ██╔══██║██╔══╝      ██╔══╝  ██║╚██╗██║██║  ██║")
        time.sleep(0.3)
        print("   ██║   ██║  ██║███████╗    ███████╗██║ ╚████║██████╔╝")
        time.sleep(0.3)
        print("   ╚═╝   ╚═╝  ╚═╝╚══════╝    ╚══════╝╚═╝  ╚═══╝╚═════╝ ")
        time.sleep(2)
        print('--- ten dobry end! ---')
        time.sleep(4)

        print('chces to zavrit? A/N')
        exitan=input('').strip().upper()
        while exitan!='A' and exitan!='B':
            print('ano nebo ne? A/N')
            exitan=input('').strip().upper()
        if exitan =='A':
            print('papa')
            time.sleep(3)
            exit()
        elif exitan=="B":
            print('no mas smulu stejnak papa')
            time.sleep(3)
            exit()

    elif abcd1=='B': #pokoj rodicu
        print('dpc broski ses uplne v pici ses kokot', end='\r')
        time.sleep(3)
        print('', end='\r')
        time.sleep(1)
        print('sel si do pokoje rodicu.. nechapu proc')
        time.sleep(1)
        print('otevrel si dvere, otec a matka te zjebali ze nespis a dostal si naprdel.')
        time.sleep(2)
        print('a rano si byl bez snidane...')
        time.sleep(3)
        print("████████╗██╗  ██╗███████╗    ███████╗███╗   ██╗██████╗ ")
        time.sleep(0.3)
        print("╚══██╔══╝██║  ██║██╔════╝    ██╔════╝████╗  ██║██╔══██╗")
        time.sleep(0.3)
        print("   ██║   ███████║█████╗      █████╗  ██╔██╗ ██║██║  ██║")
        time.sleep(0.3)
        print("   ██║   ██╔══██║██╔══╝      ██╔══╝  ██║╚██╗██║██║  ██║")
        time.sleep(0.3)
        print("   ██║   ██║  ██║███████╗    ███████╗██║ ╚████║██████╔╝")
        time.sleep(0.3)
        print("   ╚═╝   ╚═╝  ╚═╝╚══════╝    ╚══════╝╚═╝  ╚═══╝╚═════╝ ")
        time.sleep(2)
        print('--- ten spatny.. bohuzel ---')
        time.sleep(4)
        
        print('chces to zavrit? A/N')
        exitan=input('').strip().upper()
        while exitan!='A' and exitan!='B':
            print('ano nebo ne? A/N')
            exitan=input('').strip().upper()
        if exitan =='A':
            print('papa')
            time.sleep(3)
            exit()
        elif exitan=="B":
            print('no mas smulu stejnak papa')
            time.sleep(3)
            exit()
    
    elif abcd1=='C': #koupelna 
        print('otocil ses a sel is do koupelny...')
        print('co ted?')
        time.sleep(2)
        print('A --> podivas se do zrcadla a umyjes si zuby')
        print('B --> pujdes na zachod')
        ab1=input('')
        print('hele idk cos odpovedel, ale v obou pripadech te nacapali a ses bez snidane')
        time.sleep(4)
        os.system('cls')
        print("████████╗██╗  ██╗███████╗    ███████╗███╗   ██╗██████╗ ")
        time.sleep(0.3)
        print("╚══██╔══╝██║  ██║██╔════╝    ██╔════╝████╗  ██║██╔══██╗")
        time.sleep(0.3)
        print("   ██║   ███████║█████╗      █████╗  ██╔██╗ ██║██║  ██║")
        time.sleep(0.3)
        print("   ██║   ██╔══██║██╔══╝      ██╔══╝  ██║╚██╗██║██║  ██║")
        time.sleep(0.3)
        print("   ██║   ██║  ██║███████╗    ███████╗██║ ╚████║██████╔╝")
        time.sleep(0.3)
        print("   ╚═╝   ╚═╝  ╚═╝╚══════╝    ╚══════╝╚═╝  ╚═══╝╚═════╝ ")
        time.sleep(2)
        print('--- ten spatny... bohuzel ---')
        time.sleep(4)

        print('chces to zavrit? A/N')
        exitan=input('').strip().upper()
        while exitan!='A' and exitan!='B':
            print('ano nebo ne? A/N')
            exitan=input('').strip().upper()
        if exitan =='A':
            print('papa')
            time.sleep(3)
            exit()
        elif exitan=="B":
            print('no mas smulu stejnak papa')
            time.sleep(3)
            exit()

elif abodp == "B" :
    print('...no dobre, tvuj vyber')
    time.sleep(2)
    print('pohladil sis brisko, smutne zakoukal na dvere a sel spat.........')
    time.sleep(1)
    print('dobrou noc:3')
    time.sleep(3)
    print("████████╗██╗  ██╗███████╗    ███████╗███╗   ██╗██████╗ ")
    time.sleep(0.3)
    print("╚══██╔══╝██║  ██║██╔════╝    ██╔════╝████╗  ██║██╔══██╗")
    time.sleep(0.3)
    print("   ██║   ███████║█████╗      █████╗  ██╔██╗ ██║██║  ██║")
    time.sleep(0.3)
    print("   ██║   ██╔══██║██╔══╝      ██╔══╝  ██║╚██╗██║██║  ██║")
    time.sleep(0.3)
    print("   ██║   ██║  ██║███████╗    ███████╗██║ ╚████║██████╔╝")
    time.sleep(0.3)
    print("   ╚═╝   ╚═╝  ╚═╝╚══════╝    ╚══════╝╚═╝  ╚═══╝╚═════╝ ")
    time.sleep(2)
    print('--- neutralni..? ---')
    time.sleep(5)

    print('chces to zavrit? A/N')
    exitan=input('').strip().upper()
    while exitan!='A' and exitan!='B':
        print('ano nebo ne? A/N')
        exitan=input('').strip().upper()
    if exitan =='A':
        print('papa')
        time.sleep(3)
        exit()
    elif exitan=="B":
        print('no mas smulu stejnak papa')
        time.sleep(3)
        exit()

