print('spoustim program...')
print('...')
import time
time.sleep(5)
print('zdravim!')
print('')
print('tohle je ehh nejaky program no.. muzes delat tady profily nejake')
print('vyber si, co budes chtit:')
print('')
print('A - profil hrace')
print('B - hudebni profil')
print('C - vizitka')
odpovedABC=input('')
print('hej idk cos odpovedel ale me to je u zadku')
print('nejdriv se te zeptam na par basic otazek')
time.sleep(3)

print('jak se jmenujes?')
jmeno=input('')
print('aha.. tak', jmeno, ", jo..?")

time.sleep(1)
print('...')
time.sleep(2)
print('no tak nic, kdy ses narodilo vubec??')
rok=int(input(''))
print('aha.. takze ti je cca', 2026-rok, ', docela ehh idk starej nebo mladej')
vek=2026-rok
time.sleep(2)
print('tak ci tak bohuzel to poznat nemuzu prtoze idk jak to mam poznat')
time.sleep(1)
print('btw je vek spravne?')
odpoved1=input('')
if odpoved1 == "ne" or odpoved1 == "n" or odpoved1 == "nn":
    print('tak di tam kde slunce nesviti zmrde')
    time.sleep(4)
    exit()
else :
    print('tak pokracujeme')
    time.sleep(2)
    print('kde bydlis? v jakem meste?')
    mesto=input('')
    print('hustyy.. hmm')
    time.sleep(3)
    print('chces uvadet email a tel. cislo?')

    odpoved2=input('')
    if odpoved2== 'ne' or odpoved2 == "n" or odpoved1 == "nn":
        print('oka tak ted.. si muzes vybrat profil jaky chces. ted vazne')
        time.sleep(2)
        print('')
        print('\033[31m!!!POZOR!!!\033[0m')
        print('\033[31mpis JENOM capslockem (i kdyz nemusis lol) a JENOM tyhle pismena... jinak nechces videt co ti to ukaze.\033[0m')
        print('')
        time.sleep(2)
        print('A - profil hrace')
        print('B - hudebni profil')
        print('C - vizitka')
        odpovedABC=input('')
        

        if odpovedABC=="A" or odpovedABC == "a" :
            print('tak se te musim zeptat na jeste par otazek')
            time.sleep(2)
            print('jake hry mas rad? zanr a tak')
            zanr=input('')
            print('okaoka...')
            print('a jake hry jsi hral/a za posledni dva tydny nejvic?')
            hry=input('')
            print('dpc drsnak husty')
            time.sleep(2)
            print('POCKEJ jaky je tvuj bezny nickname?')
            nick=input('')

            print('tak chvilku...')
            time.sleep(10)
            print('...')
            time.sleep(5)
            print('')
            print('========================')
            print('')
            print('nickname:', nick)
            print('')
            print('jmeno:', jmeno)
            print('')
            print('rok narozeni:', rok)
            print('')
            print('vek:', vek)
            print('')
            print('oblibene zanry:', zanr)
            print('')
            print('nejvic hrane hry za posledni dva tydny:', hry)
            print('')
            print('========================')

            time.sleep(5)
            print('doufam, ze se ti to libilo! tak zase priste ;)')
            time.sleep(5)
            exit()

        elif odpovedABC=="B" or odpovedABC == "b" :
            print('tak se te musim zeptat na jeste par otazek')
            time.sleep(2)
            print('jaky zanr hudby mas nejradsi?')
            zanrhudba=input('')
            print('okaoka...')
            print('a jake umelce mas nejradeji?')
            umelce=input('')
            print('omg')
            time.sleep(2)
            print('hmm.. a kolik hodin poslouchas hudbu? pis JENOM cislo nic vic')
            hod=input('')
            print('okaoak..')
            time.sleep(2)
            print('POCKEJ jaky je tvuj nickname bezny?')
            nick=input('')

            print('tak chvilku...')
            time.sleep(10)
            print('...')
            time.sleep(5)
            print('')
            print('========================')
            print('')
            print('nickname:', nick)
            print('')
            print('jmeno:', jmeno)
            print('')
            print('rok narozeni:', rok)
            print('')
            print('vek:', vek)
            print('')
            print('oblibene zanry:', zanrhudba)
            print('')
            print('oblibene umelce:', umelce)
            print('')
            print('posloucha hudbu:', hod, "hod. ddenne cca")
            print('')
            print('========================')

            time.sleep(5)
            print('doufam, ze se ti to libilo! tak zase priste ;)')
            time.sleep(5)
            exit()

        elif odpovedABC == "c" or odpovedABC== "C" :
            print('okaoka tak pockej')
            time.sleep(10)
            print('...')
            time.sleep(5)
            print('')
            print('========================')
            print('')
            print('jmeno:', jmeno)
            print('')
            print('rok narozeni:', rok)
            print('')
            print('vek:', vek)
            print('')
            print('========================')

            time.sleep(5)
            print('doufam, ze se ti to libilo! tak zase priste ;)')
            time.sleep(5)
            exit()

        else :
            print('tak ses ddebil pis normalne')
            time.sleep(4)
            exit()


         
    elif odpoved2 == "ano":
     print('tak napis email')
     email=input('')
     print('ted tel. cislo')
     telcislo=input('')
     print('...')
     time.sleep(2)

    print('oka tak ted.. si muzes vybrat profil jaky chces. ted vazne')
    time.sleep(2)
    print('')
    print('\033[31m!!!POZOR!!!\033[0m')
    print('\033[31mpis JENOM capslockem a JENOM tyhle pismena... jinak nechces videt co ti to ukaze.\033[0m')
    print('')
    time.sleep(2)
    print('A - profil hrace')
    print('B - hudebni profil')
    print('C - vizitka')
    odpovedABC=input('')
        

    if odpovedABC=="A" or odpovedABC == "a" :
            print('tak se te musim zeptat na jeste par otazek')
            time.sleep(2)
            print('jake hry mas rad? zanr a tak')
            zanr=input('')
            print('okaoka...')
            print('a jake hry jsi hral/a za posledni dva tydny nejvic?')
            hry=input('')
            print('dpc drsnak husty')
            time.sleep(2)
            print('POCKEJ jaky je tvuj bezny nickname?')
            nick=input('')

            print('tak chvilku...')
            time.sleep(10)
            print('...')
            time.sleep(5)
            print('')
            print('========================')
            print('')
            print('nickname:', nick)
            print('')
            print('jmeno:', jmeno)
            print('')
            print('rok narozeni:', rok)
            print('')
            print('vek:', vek)
            print('')
            print('oblibene zanry:', zanr)
            print('')
            print('nejvic hrane hry za posledni dva tydny:', hry)
            print('')
            print('KONTAKTNI UDAJE')
            print('')
            print('email:', email)
            print('')
            print('tel. cislo:', telcislo)
            print('')
            print('========================')

            time.sleep(5)
            print('doufam, ze se ti to libilo! tak zase priste ;)')
            time.sleep(5)
            exit()

    elif odpovedABC=="B" or odpovedABC == "b" :
            print('tak se te musim zeptat na jeste par otazek')
            time.sleep(2)
            print('jaky zanr hudby mas nejradsi?')
            zanrhudba=input('')
            print('okaoka...')
            print('a jake umelce mas nejradeji?')
            umelce=input('')
            print('omg')
            time.sleep(2)
            print('hmm.. a kolik hodin poslouchas hudbu? pis JENOM cislo nic vic')
            hod=input('')
            print('okaoak..')
            time.sleep(2)
            print('POCKEJ jaky je tvuj nickname bezny?')
            nick=input('')

            print('tak chvilku...')
            time.sleep(10)
            print('...')
            time.sleep(5)
            print('')
            print('========================')
            print('')
            print('nickname:', nick)
            print('')
            print('jmeno:', jmeno)
            print('')
            print('rok narozeni:', rok)
            print('')
            print('vek:', vek)
            print('')
            print('oblibene zanry:', zanrhudba)
            print('')
            print('oblibene umelce:', umelce)
            print('')
            print('posloucha hudbu:', hod, "hod. ddenne cca")
            print('')
            print('KONTAKTNI UDAJE')
            print('')
            print('email:', email)
            print('')
            print('tel. cislo:', telcislo)
            print('')
            print('========================')

            time.sleep(5)
            print('doufam, ze se ti to libilo! tak zase priste ;)')
            time.sleep(5)
            exit()

    elif odpovedABC == "c" or odpovedABC== "C" :
            print('okaoka tak pockej')
            time.sleep(10)
            print('...')
            time.sleep(5)
            print('')
            print('========================')
            print('')
            print('jmeno:', jmeno)
            print('')
            print('rok narozeni:', rok)
            print('')
            print('vek:', vek)
            print('')
            print('KONTAKTNI UDAJE')
            print('')
            print('email:', email)
            print('')
            print('tel. cislo:', telcislo)
            print('')
            print('========================')

            time.sleep(5)
            print('doufam, ze se ti to libilo! tak zase priste ;)')
            time.sleep(5)
            exit()

    else :
         print('broski................ papa')
         time.sleep(4)
         exit()
