print('jdeme zjistit, kolik pismen mas ve jmene a ve meste a ve vsem moznem.')
print('')
import time
time.sleep(1)
print('napis sve jmeno')
jmeno=input('')
print("jmenujes se", jmeno, ", a tve jmeno ma", len(jmeno), "pismen")
time.sleep(1)
print('ted napis sve oblibene jidlo')
jidlo=input('')
print('tve oblibene jidlo je', jidlo, ", a je v nem", len(jidlo), "pismen")
time.sleep(1)
print('napis svou oblibenou knihu')
kniha=input('')
print('tvoje oblibena kniha se jmenuje', kniha, ", a je v nem", len(kniha), 'pismen')
time.sleep(5)

print('chces vizitku z toho udelat?')
odpoved=input('')
if odpoved=='ano' or odpoved=="jj" or odpoved == 'a' :
    print('tak pockej')
    time.sleep(5)
    jmeno=jmeno.strip()
    kniha=kniha.strip()
    jidlo=jidlo.strip()
    print('==============================')
    print('')
    print('jmeno:', jmeno)
    print('  capslock:', jmeno.upper())
    print('  NEcapslock:', jmeno.lower())
    print('  pocet znaku:', len(jmeno))
    print('  bez mezer:', jmeno.strip())
    print('oblibene jidlo:', jidlo)
    print('  capslock:', jidlo.upper())
    print('  NEcapslock:', jidlo.lower())
    print('  pocet znaku:', len(jidlo))
    print('  bez mezer:', jidlo.strip())
    print('')
    print('oblibena kniha:', kniha)
    print('  capslock:', kniha.upper())
    print('  NEcapslock:', kniha.lower())
    print('  pocet znaku:', len(kniha))
    print('  bez mezer:', kniha.strip())

elif odpoved == 'ne' or odpoved=="n" or odpoved=="nn" :
    print('tak mas smulu')

else :
    print('broski pis normalne.')
    exit()

time.sleep(5)
print('HEJ ALE POCKEJ, TY ZMRDE')
time.sleep(2)
print(jmeno.upper(), ", TY JSI PORUSIL/A ZAKON A ZA TOHLE TE VOJEBOU TY JEDNO")
time.sleep(1)
print('ze se nestydis,', jmeno.lower(), ".")
print('jde vyslech.')
print('\033[31mnic ti nepomuze ted.\033[0m')
time.sleep(1)
print('napis mesto kde bydlis.')
mesto=input('')
mesto=mesto.strip()
print('...')
time.sleep(10)
print('uz za tebou jedeme.')
time.sleep(1)

print('...hej nejses proti  jeste jedne otazce?')
odpoved1=input('')
if odpoved1=='ano' or odpoved1=="jj" or odpoved1 == 'a' :
    print('tak napis sve uzivattelske jmeno z pornhubu')
    uzivjmeno=input('')
    uzivjmeno=uzivjmeno.strip()
    print('aha.. velice zajimane jmeno,', uzivjmeno, "...")

elif odpoved1 == 'ne' or odpoved1=="n" or odpoved1=="nn" :
    print('tak didopice')

else :
    print('broski pis normalne.')
    exit()
